version: "3.7"

services:
  web-client:
    image: web-client:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
#  nexus:
#    image: sonatype/nexus3
#    volumes:
#      - "nexus-data:/nexus-data"
#    ports:
#      - "8081:8081"
#volumes:
#  nexus-data: {}
